### ISSUE TITLE
Why there is "Station Lonlat Failed"?

### ISSUE THREAD

**Issue by forestbat** [xiejx5/watershed_delineation#1]
![图片](https://user-images.githubusercontent.com/23413915/202833475-2c6b58eb-7b29-4d17-9ee8-75ef7e5a071d.png)
And this is my `total_lonlat` table:

![图片](https://user-images.githubusercontent.com/23413915/202833514-b6e1c97e-3151-47aa-9e78-c34ee6dd8a7f.png)

**Comment by xiejx5** [comment]
There should be a "Name" column after the "ID", which could be blank. Both [Supporting Information](https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1029%2F2021WR031129&file=2021WR031129-sup-0001-Supporting+Information+SI-S01.pdf) and example_station.xlsx show the details.

**Comment by forestbat** [comment]
@xiejx5 Thank for your reply, but when I start to delineation, it tells me "delineation failed".

I downloaded Asia's flow direction data which resolution is 3s from [here](https://data.hydrosheds.org/file/hydrosheds-v1-dir/as_dir_3s.zip), and cut the layer in **QGIS** to smaller size and export the layer to `GeoTIFF`.
But when I click "start", the program tells me "delineation failed" immediately, so what's my problem?

**Comment by xiejx5** [comment]
It may be caused by the format mismatch of the flow direction. Please ensure that the GeoTIFF has the format of [ArcGIS D8 flow directions](https://pro.arcgis.com/en/pro-app/2.8/tool-reference/raster-analysis/flow-direction.htm), and the data type is unsigned int8.

**Comment by forestbat** [comment]
https://paste.ubuntu.com/p/349T224wwd/
This is metadata of my tiff, and its data type is unsigned int8 too.
So I think the crash occurs because of QGIS, however I don't have ArcGIS, so I will find another computer which has ArcGIS to solve it.
And hope you can improve your code, make it allow files come from QGIS.

**Comment by forestbat** [comment]
Now I used **ArcGIS** to clip my flow direction data and data type is also unsigned int8，but watershed delineation process still failed.
Can you tell me how do you process your data when you write this paper？

**Comment by forestbat** [comment]
@xiejx5 How to use `gdal_calc.py` to make my GeoTIFF have `ArcGIS D8 flow directions` format? I don't get desirable help in [this article](https://www.osgeo.cn/gdal/programs/gdal_calc.html).

**Comment by xiejx5** [comment]
Or you can add QGIS support after the source code is released. Once the patent is released, I will release the algorithm as an open-source python package. At that time, any pull request is welcome.

**Comment by forestbat** [comment]
Ok，I know.
But even if I use "d8flowdir" data of another people who ran this tool successfully，it still failed on my computer，so I doubt it's not problem of data or tools.
Hope you can release your code earlier，and I can know what happened on my computer.
